import type { Application } from "@/types/application"

export const mockApplications: Application[] = [
  {
    id: "app-1",
    applicantId: "user-1",
    applicantName: "John Citizen",
    applicantEmail: "john.citizen@email.com",
    applicantPhone: "+1-555-0100",
    type: "passport",
    reason: "renewal",
    status: "under_review",
    submissionDate: "2024-11-25T10:30:00Z",
    lastUpdated: "2024-11-26T14:20:00Z",
    assignedTo: "user-6",
    assignedToName: "Dr. Robert Williams",
    organizationId: "org-2",
    organizationName: "Ministry of Home Affairs",
    formData: {
      currentPassportNumber: "P12345678",
      expiryDate: "2024-12-15",
      travelPlans: "Business travel to Europe in January 2025",
    },
    supportingDocuments: [
      {
        id: "doc-1",
        name: "Current Passport Scan.pdf",
        fileUrl: "/uploads/passport-scan.pdf",
        fileSize: 2048000,
        uploadDate: "2024-11-25T10:30:00Z",
        type: "proof_of_identity",
      },
      {
        id: "doc-2",
        name: "Passport Photo.jpg",
        fileUrl: "/uploads/passport-photo.jpg",
        fileSize: 512000,
        uploadDate: "2024-11-25T10:30:00Z",
        type: "other",
      },
    ],
    comments: [
      {
        id: "comment-1",
        authorId: "user-6",
        authorName: "Dr. Robert Williams",
        authorRole: "Director",
        comment: "Application received and under review. All documents appear to be in order.",
        timestamp: "2024-11-26T14:20:00Z",
        isInternal: false,
      },
    ],
    priority: "high",
    estimatedProcessingDays: 5,
  },
  {
    id: "app-2",
    applicantId: "user-1",
    applicantName: "John Citizen",
    applicantEmail: "john.citizen@email.com",
    applicantPhone: "+1-555-0100",
    type: "drivers_license",
    reason: "first_time",
    status: "submitted",
    submissionDate: "2024-11-27T09:00:00Z",
    lastUpdated: "2024-11-27T09:00:00Z",
    organizationId: "org-2",
    organizationName: "Ministry of Home Affairs",
    formData: {
      dateOfBirth: "1990-05-15",
      address: "123 Main Street, Capital City",
      licenseType: "Class B - Standard Vehicle",
      testDate: "2024-11-20",
      testResult: "Passed",
    },
    supportingDocuments: [
      {
        id: "doc-3",
        name: "National ID.pdf",
        fileUrl: "/uploads/national-id.pdf",
        fileSize: 1024000,
        uploadDate: "2024-11-27T09:00:00Z",
        type: "proof_of_identity",
      },
      {
        id: "doc-4",
        name: "Driving Test Certificate.pdf",
        fileUrl: "/uploads/test-certificate.pdf",
        fileSize: 800000,
        uploadDate: "2024-11-27T09:00:00Z",
        type: "other",
      },
    ],
    comments: [],
    priority: "medium",
    estimatedProcessingDays: 10,
  },
  {
    id: "app-3",
    applicantId: "user-8",
    applicantName: "Emily Thompson",
    applicantEmail: "emily.t@email.com",
    applicantPhone: "+1-555-0200",
    type: "national_id",
    reason: "replacement_lost",
    status: "additional_info_required",
    submissionDate: "2024-11-20T11:00:00Z",
    lastUpdated: "2024-11-24T15:30:00Z",
    assignedTo: "user-6",
    assignedToName: "Dr. Robert Williams",
    organizationId: "org-2",
    organizationName: "Ministry of Home Affairs",
    formData: {
      previousIdNumber: "ID-987654321",
      dateReported: "2024-11-15",
      policeReportNumber: "PR-2024-11-0015",
    },
    supportingDocuments: [
      {
        id: "doc-5",
        name: "Police Report.pdf",
        fileUrl: "/uploads/police-report.pdf",
        fileSize: 1536000,
        uploadDate: "2024-11-20T11:00:00Z",
        type: "other",
      },
    ],
    comments: [
      {
        id: "comment-2",
        authorId: "user-6",
        authorName: "Dr. Robert Williams",
        authorRole: "Director",
        comment: "Please provide proof of residence (utility bill or bank statement from last 3 months).",
        timestamp: "2024-11-24T15:30:00Z",
        isInternal: false,
      },
    ],
    priority: "medium",
    estimatedProcessingDays: 7,
  },
  {
    id: "app-4",
    applicantId: "user-9",
    applicantName: "Michael Chen",
    applicantEmail: "m.chen@email.com",
    applicantPhone: "+1-555-0300",
    type: "passport",
    reason: "first_time",
    status: "approved",
    submissionDate: "2024-11-10T14:00:00Z",
    lastUpdated: "2024-11-22T16:00:00Z",
    assignedTo: "user-6",
    assignedToName: "Dr. Robert Williams",
    reviewedBy: "user-6",
    reviewedByName: "Dr. Robert Williams",
    reviewDate: "2024-11-15T10:00:00Z",
    approvedBy: "user-6",
    approvedByName: "Dr. Robert Williams",
    approvalDate: "2024-11-22T16:00:00Z",
    organizationId: "org-2",
    organizationName: "Ministry of Home Affairs",
    formData: {
      dateOfBirth: "1988-03-22",
      placeOfBirth: "Capital City",
      nationality: "National",
      occupation: "Software Engineer",
    },
    supportingDocuments: [
      {
        id: "doc-6",
        name: "Birth Certificate.pdf",
        fileUrl: "/uploads/birth-cert.pdf",
        fileSize: 1200000,
        uploadDate: "2024-11-10T14:00:00Z",
        type: "birth_certificate",
      },
      {
        id: "doc-7",
        name: "Passport Photo.jpg",
        fileUrl: "/uploads/photo.jpg",
        fileSize: 600000,
        uploadDate: "2024-11-10T14:00:00Z",
        type: "other",
      },
    ],
    comments: [
      {
        id: "comment-3",
        authorId: "user-6",
        authorName: "Dr. Robert Williams",
        authorRole: "Director",
        comment: "All documents verified. Application approved. Document will be issued within 2 business days.",
        timestamp: "2024-11-22T16:00:00Z",
        isInternal: false,
      },
    ],
    priority: "high",
    estimatedProcessingDays: 5,
  },
  {
    id: "app-5",
    applicantId: "user-10",
    applicantName: "Sarah Martinez",
    applicantEmail: "s.martinez@email.com",
    applicantPhone: "+1-555-0400",
    type: "birth_certificate",
    reason: "first_time",
    status: "rejected",
    submissionDate: "2024-11-18T09:30:00Z",
    lastUpdated: "2024-11-21T11:00:00Z",
    assignedTo: "user-6",
    assignedToName: "Dr. Robert Williams",
    reviewedBy: "user-6",
    reviewedByName: "Dr. Robert Williams",
    reviewDate: "2024-11-21T11:00:00Z",
    rejectionReason:
      "Insufficient documentation. Hospital birth record not provided. Please submit official hospital birth documentation.",
    organizationId: "org-2",
    organizationName: "Ministry of Home Affairs",
    formData: {
      childName: "Baby Martinez",
      dateOfBirth: "2024-11-01",
      placeOfBirth: "Central Hospital",
      motherName: "Sarah Martinez",
      fatherName: "Carlos Martinez",
    },
    supportingDocuments: [
      {
        id: "doc-8",
        name: "Parents IDs.pdf",
        fileUrl: "/uploads/parent-ids.pdf",
        fileSize: 2048000,
        uploadDate: "2024-11-18T09:30:00Z",
        type: "proof_of_identity",
      },
    ],
    comments: [
      {
        id: "comment-4",
        authorId: "user-6",
        authorName: "Dr. Robert Williams",
        authorRole: "Director",
        comment:
          "Missing hospital birth documentation. Please obtain and submit official birth record from Central Hospital.",
        timestamp: "2024-11-21T11:00:00Z",
        isInternal: false,
      },
    ],
    priority: "high",
    estimatedProcessingDays: 3,
  },
]
