import type { Authority } from "@/types/authority"

export const mockAuthorities: Authority[] = [
  {
    id: "auth-1",
    name: "National University",
    type: "education",
    logo: "/generic-university-logo.png",
    description: "Leading educational institution",
    contactEmail: "admin@university.edu",
    contactPhone: "+1-555-1000",
    website: "https://university.edu",
    status: "active",
    registrationDate: "2024-01-10T00:00:00Z",
    documentsIssued: 1250,
    verificationRate: 98.5,
    authorizedOfficers: [
      {
        id: "officer-1",
        name: "Dr. Sarah Johnson",
        email: "admin@university.edu",
        position: "Registrar",
        canIssue: ["degree", "transcript"],
        addedDate: "2024-01-10T00:00:00Z",
      },
    ],
  },
  {
    id: "auth-2",
    name: "Ministry of Health",
    type: "government",
    logo: "/government-health-ministry-logo.jpg",
    description: "National health authority",
    contactEmail: "records@health.gov",
    contactPhone: "+1-555-2000",
    website: "https://health.gov",
    status: "active",
    registrationDate: "2024-01-05T00:00:00Z",
    documentsIssued: 5420,
    verificationRate: 99.2,
    authorizedOfficers: [
      {
        id: "officer-2",
        name: "Dr. Robert Williams",
        email: "r.williams@health.gov",
        position: "Director of Records",
        canIssue: ["birth_certificate"],
        addedDate: "2024-01-05T00:00:00Z",
      },
    ],
  },
  {
    id: "auth-3",
    name: "Department of Motor Vehicles",
    type: "government",
    logo: "/dmv-government-logo.jpg",
    description: "Motor vehicle licensing authority",
    contactEmail: "licensing@dmv.gov",
    contactPhone: "+1-555-3000",
    website: "https://dmv.gov",
    status: "active",
    registrationDate: "2024-01-08T00:00:00Z",
    documentsIssued: 3180,
    verificationRate: 97.8,
    authorizedOfficers: [],
  },
  {
    id: "auth-4",
    name: "Land Registry Office",
    type: "government",
    logo: "/land-registry-office-logo.jpg",
    description: "Property and land title management",
    contactEmail: "records@landregistry.gov",
    contactPhone: "+1-555-4000",
    website: "https://landregistry.gov",
    status: "active",
    registrationDate: "2024-01-12T00:00:00Z",
    documentsIssued: 892,
    verificationRate: 99.5,
    authorizedOfficers: [],
  },
  {
    id: "auth-5",
    name: "National Tax Authority",
    type: "financial",
    logo: "/tax-authority-logo.jpg",
    description: "Tax certification and clearance",
    contactEmail: "certificates@tax.gov",
    contactPhone: "+1-555-5000",
    website: "https://tax.gov",
    status: "active",
    registrationDate: "2024-01-20T00:00:00Z",
    documentsIssued: 2340,
    verificationRate: 96.7,
    authorizedOfficers: [],
  },
]
