import type { Organization } from "@/types/organization"

export const mockOrganizations: Organization[] = [
  {
    id: "org-1",
    name: "Ministry of Education",
    type: "ministry",
    logo: "/ministry-education-logo.jpg",
    description: "National education authority responsible for all educational certifications",
    contactEmail: "contact@education.gov",
    contactPhone: "+1-555-1000",
    address: "100 Education Street, Capital City",
    website: "https://education.gov",
    status: "active",
    registrationDate: "2024-01-01T00:00:00Z",
    documentsIssued: 15420,
    verificationRate: 99.2,
    digitalSignature: {
      publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...",
      algorithm: "RSA-SHA256",
      issuedDate: "2024-01-01T00:00:00Z",
      expiryDate: "2029-01-01T00:00:00Z",
      certificateUrl: "/certificates/ministry-education.pem",
      status: "active",
    },
    administrators: [
      {
        id: "admin-1",
        userId: "user-2",
        name: "Dr. Sarah Johnson",
        email: "s.johnson@education.gov",
        position: "Director of Certification",
        permissions: ["issue_documents", "approve_documents", "sign_documents", "view_analytics"],
        canSign: true,
        signatureUrl: "/signatures/sarah-johnson.png",
        addedDate: "2024-01-01T00:00:00Z",
        status: "active",
      },
      {
        id: "admin-2",
        userId: "user-5",
        name: "Prof. Michael Anderson",
        email: "m.anderson@education.gov",
        position: "Deputy Director",
        permissions: ["issue_documents", "approve_documents", "sign_documents"],
        canSign: true,
        signatureUrl: "/signatures/michael-anderson.png",
        addedDate: "2024-01-05T00:00:00Z",
        status: "active",
      },
    ],
    allowedDocumentTypes: ["degree", "transcript"],
  },
  {
    id: "org-2",
    name: "Ministry of Home Affairs",
    type: "ministry",
    logo: "/ministry-home-affairs-logo.jpg",
    description: "Responsible for national identification and civil registration",
    contactEmail: "contact@homeaffairs.gov",
    contactPhone: "+1-555-2000",
    address: "200 Government Avenue, Capital City",
    website: "https://homeaffairs.gov",
    status: "active",
    registrationDate: "2024-01-01T00:00:00Z",
    documentsIssued: 28340,
    verificationRate: 99.5,
    digitalSignature: {
      publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...",
      algorithm: "RSA-SHA256",
      issuedDate: "2024-01-01T00:00:00Z",
      expiryDate: "2029-01-01T00:00:00Z",
      certificateUrl: "/certificates/ministry-home-affairs.pem",
      status: "active",
    },
    administrators: [
      {
        id: "admin-3",
        userId: "user-6",
        name: "Dr. Robert Williams",
        email: "r.williams@homeaffairs.gov",
        position: "Director of Civil Registration",
        permissions: ["issue_documents", "approve_documents", "sign_documents", "manage_users", "view_analytics"],
        canSign: true,
        signatureUrl: "/signatures/robert-williams.png",
        addedDate: "2024-01-01T00:00:00Z",
        status: "active",
      },
    ],
    allowedDocumentTypes: ["birth_certificate", "national_id", "passport", "marriage_certificate"],
  },
  {
    id: "org-3",
    name: "National Land Registry",
    type: "registry",
    logo: "/land-registry-logo.jpg",
    description: "Property and land title registration authority",
    contactEmail: "info@landregistry.gov",
    contactPhone: "+1-555-3000",
    address: "300 Registry Road, Capital City",
    website: "https://landregistry.gov",
    status: "active",
    registrationDate: "2024-01-01T00:00:00Z",
    documentsIssued: 8920,
    verificationRate: 99.8,
    digitalSignature: {
      publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...",
      algorithm: "RSA-SHA256",
      issuedDate: "2024-01-01T00:00:00Z",
      expiryDate: "2029-01-01T00:00:00Z",
      certificateUrl: "/certificates/land-registry.pem",
      status: "active",
    },
    administrators: [
      {
        id: "admin-4",
        userId: "user-7",
        name: "James Morrison",
        email: "j.morrison@landregistry.gov",
        position: "Chief Registrar",
        permissions: ["issue_documents", "approve_documents", "sign_documents", "view_analytics", "revoke_documents"],
        canSign: true,
        signatureUrl: "/signatures/james-morrison.png",
        addedDate: "2024-01-01T00:00:00Z",
        status: "active",
      },
    ],
    allowedDocumentTypes: ["property_deed", "land_title"],
  },
  {
    id: "org-4",
    name: "National University",
    type: "university",
    logo: "/national-university-logo.jpg",
    description: "Premier national university for higher education",
    contactEmail: "registrar@nationaluniversity.edu",
    contactPhone: "+1-555-4000",
    address: "400 University Boulevard, Capital City",
    website: "https://nationaluniversity.edu",
    status: "active",
    registrationDate: "2024-01-10T00:00:00Z",
    documentsIssued: 5240,
    verificationRate: 98.5,
    digitalSignature: {
      publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...",
      algorithm: "RSA-SHA256",
      issuedDate: "2024-01-10T00:00:00Z",
      expiryDate: "2029-01-10T00:00:00Z",
      certificateUrl: "/certificates/national-university.pem",
      status: "active",
    },
    administrators: [],
    allowedDocumentTypes: ["degree", "transcript"],
  },
  {
    id: "org-5",
    name: "Central Hospital",
    type: "hospital",
    logo: "/central-hospital-logo.jpg",
    description: "National healthcare facility",
    contactEmail: "records@centralhospital.health",
    contactPhone: "+1-555-5000",
    address: "500 Healthcare Avenue, Capital City",
    website: "https://centralhospital.health",
    status: "pending",
    registrationDate: "2024-11-20T00:00:00Z",
    documentsIssued: 0,
    verificationRate: 0,
    digitalSignature: {
      publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...",
      algorithm: "RSA-SHA256",
      issuedDate: "2024-11-20T00:00:00Z",
      expiryDate: "2029-11-20T00:00:00Z",
      certificateUrl: "/certificates/central-hospital.pem",
      status: "active",
    },
    administrators: [],
    allowedDocumentTypes: ["birth_certificate"],
  },
]
