import type { ShareRequest } from "@/types/sharing"

export const mockShares: ShareRequest[] = [
  {
    id: "share-1",
    documentId: "doc-2",
    documentName: "Bachelor of Science in Computer Science",
    sharedBy: "user-1",
    sharedWith: "employer@techcorp.com",
    purpose: "Employment Verification",
    permissions: ["view", "verify"],
    duration: "7d",
    expiresAt: "2024-12-05T10:00:00Z",
    status: "active",
    accessToken: "tok_1234567890abcdef",
    createdAt: "2024-11-28T10:00:00Z",
    accessCount: 3,
  },
  {
    id: "share-2",
    documentId: "doc-3",
    documentName: "Driver's License",
    sharedBy: "user-1",
    sharedWith: "rental@carcompany.com",
    purpose: "Car Rental Verification",
    permissions: ["view"],
    duration: "24h",
    expiresAt: "2024-11-29T09:00:00Z",
    status: "active",
    accessToken: "tok_abcdef1234567890",
    createdAt: "2024-11-28T09:00:00Z",
    accessCount: 1,
  },
  {
    id: "share-3",
    documentId: "doc-4",
    documentName: "Property Deed - 123 Main Street",
    sharedBy: "user-1",
    sharedWith: "loan@bank.com",
    purpose: "Mortgage Application",
    permissions: ["view", "download", "verify"],
    duration: "7d",
    expiresAt: "2024-11-20T00:00:00Z",
    status: "expired",
    accessToken: "tok_xyz9876543210abc",
    createdAt: "2024-11-13T00:00:00Z",
    accessCount: 5,
  },
]
